Feature/user
ildarnarbek/TaskManager pull request #12
Opened 2020-05-10 00:11 UTC by ildarnarbek

2020-05-10 16:57 UTC, artempartos commented
тут тоже самое - куча коммитов не относящихся к задаче
смержить задачу про таски, отребейзить эту, интерактивным ребейзом удалить ненужным коммиты из ветки

2020-05-10 20:18 UTC, artempartos requested changes

2020-05-10 20:18 UTC, artempartos commented on app/controllers/web/application_controller.rb
> +  include Concerns::AuthHelper
вот тут внимательней посмотри.

Тебе надо посмотреть как работает автозагрузка, у тебя так не будет работать и это почему у тебя ломается.

Как найти в чем дело
1) Пример статьи, в которой делают концерн, но инклуд ты там увидишь немного другой, посмотри разницу
https://www.sitepoint.com/dry-off-your-rails-code-with-activesupportconcerns/
2) Прочитать статью как работает autoload в рельсах и распечатать какие пути находятся в autoload_path
https://guides.rubyonrails.org/autoloading_and_reloading_constants.html
https://til.hashrocket.com/posts/efb9003f8c-rails-autoload-paths
3) прочитать issue https://github.com/rails/rails/issues/36054

2020-05-11 15:08 UTC, ildarnarbek commented on app/controllers/web/application_controller.rb
> +  include Concerns::AuthHelper
irb(main):002:0> puts ActiveSupport::Dependencies.autoload_paths
/app/app/channels
/app/app/controllers
/app/app/controllers/concerns
/app/app/forms
/app/app/helpers
/app/app/jobs
/app/app/mailers
/app/app/models
/app/app/models/concerns
/bundle_cache/ruby/2.7.0/gems/actiontext-6.0.2.2/app/helpers
/bundle_cache/ruby/2.7.0/gems/actiontext-6.0.2.2/app/models
/bundle_cache/ruby/2.7.0/gems/actionmailbox-6.0.2.2/app/controllers
/bundle_cache/ruby/2.7.0/gems/actionmailbox-6.0.2.2/app/jobs
/bundle_cache/ruby/2.7.0/gems/actionmailbox-6.0.2.2/app/models
/bundle_cache/ruby/2.7.0/gems/activestorage-6.0.2.2/app/controllers
/bundle_cache/ruby/2.7.0/gems/activestorage-6.0.2.2/app/controllers/concerns
/bundle_cache/ruby/2.7.0/gems/activestorage-6.0.2.2/app/jobs
/bundle_cache/ruby/2.7.0/gems/activestorage-6.0.2.2/app/models
/app/test/mailers/previews

2020-05-11 18:57 UTC, pn-y requested changes

2020-05-11 18:57 UTC, pn-y commented on test/controllers/web/developers_controller_test.rb
> +    assert_response :redirect
```ruby
def create
  redirect_to(:board)
end
```
Вот такой вот экшон будет проходить твой тест. Но пользователь создаваться не будет. Это плохо.
Надо проверить в тесте что создается пользователь.

2020-05-11 18:57 UTC, pn-y commented on app/controllers/concerns/auth_helper.rb
> +  end
Что-то с отступами

2020-05-14 10:54 UTC, Andrew8xx8 approved these changes

2020-05-14 11:35 UTC, merged