Feature/admins panel
ildarnarbek/TaskManager pull request #16
Opened 2020-05-15 11:25 UTC by ildarnarbek

2020-05-15 19:09 UTC, artempartos commented
у тебя в layout приложения криво встален код, из за этого ссылки вывались из навбара

2020-05-15 19:28 UTC, artempartos requested changes

2020-05-15 19:28 UTC, artempartos commented on test/controllers/admin_controller_test.rb
> +class Admin::UsersControllerTest < ActionController::TestCase
у тебя нет такого контроллера, это тест юзеров админки, а файл называется admin_controller_test, скорее всего в обучении опечатка

2020-05-16 16:20 UTC, pn-y requested changes

2020-05-16 16:20 UTC, pn-y commented on test/controllers/admin/users_controller_test.rb
> +    assert_response :redirect
Не проверяется суть™ экшона. 
Экшон с одним редиректом все еще будет проходить этот тест.

2020-05-16 16:20 UTC, pn-y commented on test/controllers/admin/users_controller_test.rb
> +    assert_response :redirect
Не проверяется суть™ экшона. 
Экшон с одним редиректом все еще будет проходить этот тест.

2020-05-16 16:20 UTC, pn-y commented on test/controllers/admin/users_controller_test.rb
> +    assert_response :redirect
Не проверяется суть™ экшона. 
Экшон с одним редиректом все еще будет проходить этот тест.

2020-05-16 16:20 UTC, pn-y commented on test/controllers/web/boards_controller_test.rb
> +  setup do
setup следует располагать в самом начале. Иначе порядок не логичен

2020-05-18 09:38 UTC, pn-y requested changes

2020-05-18 09:38 UTC, pn-y commented on app/controllers/admin/users_controller.rb
> +      render :new_admin_user_url
Мне кажется это не работает

2020-05-18 09:38 UTC, pn-y commented on test/controllers/admin/users_controller_test.rb
> +    created_user = User.find_by(first_name: user[:first_name])
first_name - не уникальный атрибут. Искать по нему - плохая идея.

2020-05-18 09:46 UTC, ildarnarbek commented on app/controllers/admin/users_controller.rb
> +      render :new_admin_user_url
Уточни пожалуйста, почему не работает?

2020-05-19 14:43 UTC, pn-y requested changes

2020-05-19 14:43 UTC, pn-y commented on test/controllers/admin/users_controller_test.rb
> +    created_user.present?
assert потерял

2020-05-20 10:05 UTC, pn-y approved these changes

2020-05-20 10:27 UTC, merged