Feature/api
ildarnarbek/TaskManager pull request #17
Opened 2020-05-17 13:06 UTC by ildarnarbek

2020-05-18 09:39 UTC, pn-y requested changes

2020-05-18 09:39 UTC, pn-y commented on app/controllers/api/v1/application_controller.rb
> +class Api::V1::ApplicationController < ApplicationController
Пропущен 1 уровень в иерархии.
Слева - третий уровень
Справа - первый.

2020-05-18 09:39 UTC, pn-y commented on app/controllers/api/v1/tasks_controller.rb
> +    tasks = Task.all
`all` не нужон

2020-05-18 10:27 UTC, ildarnarbek commented on app/controllers/api/v1/application_controller.rb
> +class Api::V1::ApplicationController < ApplicationController
Api::V1::ApplicationController < **Api**::ApplicationController

Про то что **Api** пропустил справа понял, а про слева не понимаю почему пропустил, подскажи пожалуйста

2020-05-19 14:45 UTC, pn-y requested changes

2020-05-19 14:45 UTC, pn-y commented on app/controllers/api/v1/tasks_controller.rb
> +  respond_to :json
вынеси на уровень ApplicationController

2020-05-19 14:45 UTC, pn-y commented on app/controllers/api/v1/tasks_controller.rb
> +  def self.responder
вынеси на уровень ApplicationController

2020-05-19 14:45 UTC, pn-y commented on test/controllers/api/v1/tasks_controller_test.rb
> +    assert created_task.present?
Бесполезная проверка.  Если не будет такого таска - упадет на 26 строке

2020-05-20 10:06 UTC, pn-y commented on app/controllers/api/v1/tasks_controller.rb
> +
Лишние отступы почисти

2020-05-20 10:07 UTC, pn-y approved these changes

2020-05-20 10:29 UTC, merged