Feature/tasks
ildarnarbek/TaskManager pull request #21
Opened 2020-05-27 17:16 UTC by ildarnarbek

2020-05-31 23:45 UTC, ildarnarbek commented
В файле   app/javascript/forms/TaskForm.js закоментирован участок, тк ввиду того что он создавал поля author_id и assignee_Id и присваивал им значения null  возникала ошибка  с созданием задачи. Удалив эти строки все работает. Вопрос, можно ли так сделать или есть другое решение?

2020-06-01 13:04 UTC, pn-y requested changes

2020-06-01 13:04 UTC, pn-y commented on app/controllers/api/v1/tasks_controller.rb
> +    puts "create!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!1"
Не должно быть этого тут

2020-06-01 13:04 UTC, pn-y commented on app/javascript/components/TaskBoard/TaskBoard.js
> +        // console.log('state');
и этого не должно быть

2020-06-01 13:04 UTC, pn-y commented on app/javascript/forms/TaskForm.js
> +      // assigneeId: propOr(null, 'id', task.assignee),
нельзя менять кому назначена задача?!

2020-06-01 13:04 UTC, pn-y commented on app/javascript/packs/application.js
> +import TaskBoard from '../components/TaskBoard';
не используй относительные пути наверх

2020-06-01 13:04 UTC, pn-y commented on app/javascript/repositories/TasksRepository.js
> +  update(id, task = {}) {
Не надо здесь использовать дефолтные параметры. Они могут лишь скрыть ошибку, и ни чем не помогают.

2020-06-01 13:42 UTC, ildarnarbek commented on app/javascript/forms/TaskForm.js
> +      // assigneeId: propOr(null, 'id', task.assignee),
Вот тут у меня и возник вопрос, я его сверху написал. Если оставить эти строки то не создается задача, так как передается author_id: null и почему то из за этого не создается задача.  В следующем задании можно менять поэтому эту строку нужно будет вернуть.

2020-06-02 10:12 UTC, pn-y requested changes

2020-06-02 10:12 UTC, pn-y commented on app/javascript/components/ColumnHeader/ColumnHeader.js
> +      <IconButton aria-label="Load more" onClick={() => handleLoadMore()}>
`onClick={handleLoadMore}`

2020-06-02 10:12 UTC, pn-y commented on app/javascript/forms/TaskForm.js
> +      // authorId: propOr(null, 'id', task.author),
Коммент

2020-06-03 10:51 UTC, pn-y requested changes

2020-06-03 10:51 UTC, pn-y commented on app/javascript/components/ColumnHeader/ColumnHeader.js
> +  let loadButton;
будто бы есть другое решение для этого

2020-06-03 11:44 UTC, pn-y approved these changes

2020-06-03 11:50 UTC, merged