Feature/assignee for tasks
ildarnarbek/TaskManager pull request #22
Opened 2020-06-03 10:48 UTC by ildarnarbek

2020-06-03 11:47 UTC, pn-y requested changes

2020-06-03 11:47 UTC, pn-y commented on app/javascript/components/EditPopup/components/Form/Form.js
> +import TaskPresenter from '../../../presenters/TaskPresenter';
Не стоит использовать относительные пути наверх

2020-06-03 11:47 UTC, pn-y commented on config/routes.rb
> +
пустые строки

2020-06-04 10:33 UTC, pn-y requested changes

2020-06-04 10:33 UTC, pn-y commented on app/javascript/components/AddPopup/AddPopup.js
> +import TaskPresenter from '../presenters/TaskPresenter';
что было на предыдущем ревью про относительные пути вверх?

2020-06-05 12:19 UTC, pn-y requested changes

2020-06-05 12:19 UTC, pn-y commented on app/javascript/components/AddPopup/AddPopup.js
> +import TaskPresenter from 'components/presenters/TaskPresenter';
презентер это НЕ компонент. Это отдельная абстракция

2020-06-05 12:19 UTC, pn-y commented on app/javascript/components/AddPopup/AddPopup.js
> +              value={task.author}
Презентер потерялся

2020-06-11 15:45 UTC, helmq requested changes

2020-06-11 15:45 UTC, helmq commented on app/javascript/components/EditPopup/components/Form/Form.js
>  };
В propTypes для таски тоже нужно использовать презентер

2020-06-11 15:45 UTC, helmq commented on app/javascript/components/UserSelect/UserSelect.js
> +  onChange: () => {},
Имеет ли смысл данный компонент без этой функции?

2020-06-11 15:45 UTC, helmq commented on app/serializers/user_serializer.rb
> +  end
Что-то не так с отступами

2020-06-11 15:45 UTC, helmq commented on app/javascript/components/UserSelect/UserSelect.js
> +            getOptionValue={(user) => user.id}
В целом допустимо, но лучше использовать презентер

2020-06-11 15:45 UTC, helmq commented on config/routes.rb
> +
Кажется лишний пробел :)
Обычно рубокоп должен ругаться на такое

2020-06-11 19:01 UTC, ildarnarbek commented on app/javascript/components/UserSelect/UserSelect.js
> +            getOptionValue={(user) => user.id}
В задании написано id оставить как  id  а для остального использовать презентер

2020-06-11 19:02 UTC, ildarnarbek commented on app/javascript/components/EditPopup/components/Form/Form.js
>  };
Немного не понял, можешь описать по подробнее?

2020-06-12 04:04 UTC, helmq commented on app/javascript/components/UserSelect/UserSelect.js
> +            getOptionValue={(user) => user.id}
Покажи где это написано

2020-06-12 04:04 UTC, helmq commented on app/javascript/components/EditPopup/components/Form/Form.js
>  };
В уроке про презентеры есть пример, перечитай

2020-06-13 15:28 UTC, ildarnarbek commented on app/javascript/components/UserSelect/UserSelect.js
> +            getOptionValue={(user) => user.id}
https://learn.dualboot.ru/lessons/10/practice/4

2020-06-13 17:24 UTC, helmq approved these changes

2020-06-13 23:50 UTC, merged