Feature/action mailer
ildarnarbek/TaskManager pull request #31
Opened 2020-06-18 23:52 UTC by ildarnarbek

2020-06-21 11:08 UTC, pn-y requested changes

2020-06-21 11:08 UTC, pn-y commented on app/controllers/web/password_resets_controller.rb
> +      render(:index)
При успехе наверняка тебе нужен редирект

2020-06-21 11:08 UTC, pn-y commented on app/controllers/web/password_resets_controller.rb
> +    @password_reset=PasswordResetForm.new(password_reset_params)
С пробелами беда какая то

2020-06-21 11:08 UTC, pn-y commented on app/controllers/web/password_resets_controller.rb
> +    if @user.password_reset_sent_at < 24.hour.ago
В контроллерах у тебя не должно быть бизнесовой логики

2020-06-21 11:08 UTC, pn-y commented on app/controllers/web/password_resets_controller.rb
> +      @user.change_time_reset_token(@user)
а зачем тебе обновлять время?

2020-06-21 11:08 UTC, pn-y commented on app/controllers/web/password_resets_controller.rb
> +    params.require(:developer).permit(:password)
Подтверждение пароля не требуется?

2020-06-21 11:08 UTC, pn-y commented on app/forms/password_reset_form.rb
> +        errors.add(:email, "email doesn't match")
Что это значит? С чем не совпадает емейл?

2020-06-21 11:08 UTC, pn-y commented on test/controllers/web/password_resets_controller_test.rb
> +
остальные тесты где?

2020-06-21 11:08 UTC, pn-y commented on db/migrate/20200617120659_add_password_reset_to_users.rb
> +    add_column :users, :password_reset_token, :string
А если такой токен уже будет?

2020-06-21 11:08 UTC, pn-y commented on app/models/user.rb
> +  def generate_token(column)
Выглядит не очень рабочим

2020-06-21 11:08 UTC, pn-y commented on app/models/user.rb
> +      self[column] = SecureRandom.urlsafe_base64
Доступ в стиле хеша лучше не использовать т.к. это внутренняя имплементация

2020-06-22 18:12 UTC, ildarnarbek commented on app/controllers/web/password_resets_controller.rb
> +      @user.change_time_reset_token(@user)
За счет обновления времени у меня протухает токен.
Это единственное что пришло в голову.
Можешь подсказать как лучше сделать?

2020-06-22 18:12 UTC, ildarnarbek commented on app/controllers/web/password_resets_controller.rb
> +    if @user.password_reset_sent_at < 24.hour.ago
Перенести в модели?

2020-06-22 18:12 UTC, ildarnarbek commented on app/controllers/web/password_resets_controller.rb
> +      render(:index)
Ну у меня показывается пользователю страница что все прошло успешно, а зачем редирект?

2020-06-22 18:12 UTC, ildarnarbek commented on db/migrate/20200617120659_add_password_reset_to_users.rb
> +    add_column :users, :password_reset_token, :string
Немного не понял суть вопроса. можешь подробнее подсказать какая может быть проблема?

2020-06-23 12:27 UTC, pn-y commented on app/controllers/web/password_resets_controller.rb
> +      @user.change_time_reset_token(@user)
Обнулить его

2020-06-23 12:27 UTC, pn-y commented on app/controllers/web/password_resets_controller.rb
> +    if @user.password_reset_sent_at < 24.hour.ago
как вариант

2020-06-23 12:27 UTC, pn-y commented on app/controllers/web/password_resets_controller.rb
> +      render(:index)
пушто у тебя экшон выполнился

2020-06-23 12:27 UTC, pn-y commented on db/migrate/20200617120659_add_password_reset_to_users.rb
> +    add_column :users, :password_reset_token, :string
у двух юзеров одинаковый  токен

2020-06-25 20:31 UTC, pn-y requested changes

2020-06-25 20:31 UTC, pn-y commented on test/controllers/web/password_resets_controller_test.rb
> +  end
дестрой где?

2020-06-25 20:31 UTC, pn-y commented on db/migrate/20200617120659_add_password_reset_to_users.rb
> +    add_column :users, :password_reset_token, :string
^^^ не решен коммент

2020-06-28 22:50 UTC, ildarnarbek commented on test/controllers/web/password_resets_controller_test.rb
> +  end
Я вот не очень понял зачем в данном случае дестрой? можешь подробнее сказать ?

2020-06-30 20:16 UTC, pn-y requested changes

2020-06-30 20:16 UTC, pn-y commented on app/controllers/web/password_resets_controller.rb
> +    render(:edit)
а зачем еще раз рендер?

2020-06-30 20:16 UTC, pn-y commented on app/controllers/web/password_resets_controller.rb
> +    if !@user.has_active_token?(@user)
ты вызываешь метод на инстансе, и передаешь туда же инстанс. Будто бы оно и без аргументов должно работать

2020-06-30 20:16 UTC, pn-y commented on app/views/user_mailer/password_reset.html.slim
> +<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
Это точно здесь нужно?

2020-06-30 20:16 UTC, pn-y commented on db/schema.rb
> +  create_table "active_storage_attachments", force: :cascade do |t|
Эти таблицы не из этого МР. Не должно быть их тут

2020-06-30 20:16 UTC, pn-y commented on db/schema.rb
> +ActiveRecord::Schema.define(version: 2020_06_24_123802) do
Нет записи об уникальном индексе password_reset_token

2020-07-06 21:35 UTC, artempartos approved these changes

2020-07-07 22:22 UTC, merged