added models
ildarnarbek/TaskManager pull request #6
Opened 2020-05-01 19:43 UTC by ildarnarbek

2020-05-04 16:55 UTC, Andrew8xx8 requested changes

2020-05-04 16:55 UTC, Andrew8xx8 commented on test/models/admin_test.rb
> +require 'test_helper'
Пустые тесты надо удалить

2020-05-04 16:55 UTC, Andrew8xx8 commented on test/fixtures/tasks.yml
> +one:
А вместо фикстур использовать фабрики, то есть все файлы в папке`fixtures` надо удалить. Пройди задание еще раз внимательнее, потому что там используется команда для генерации моделей с флагами, которые игнорируют генерацию фикстур и меняют на генерацию фабрик, при этом гем `factory_bot` должен тоже быть установлен

2020-05-05 17:48 UTC, Andrew8xx8 requested changes
Мы обновили это задание, фабрики нужно зарефакторить, чтобы использовалась генерация значений, вместо статически заданных

2020-05-06 21:30 UTC, ildarnarbek commented
Я не уверен что правильно сделал, но сделал как понял. Если нужно будет поправить можешь подробнее рассказать, что не так и как сделать правильно.

2020-05-07 14:26 UTC, pn-y requested changes

2020-05-07 14:26 UTC, pn-y commented on test/factories/tasks.rb
> +    sequence(:author_id) { |n| n }
Нельзя так задавать айдишники. У тебя они будут расти по единице, а сущностей таких в базе - не будет.

2020-05-07 14:26 UTC, pn-y commented on test/factories/tasks.rb
> +    sequence(:name) { |n| "name#{n}" }
Лучше вынести все сиквенсы в отдельный файл и задать им алиасы. Так будет проще управлять ими.

2020-05-07 14:26 UTC, pn-y commented on test/factories/users.rb
> +    sequence :type do |n|
Плохая идея. 
Захочешь создать админа - будешь создавать пользователей пока не выпадет админ?
Создай трейты для каждого типа.

2020-05-09 17:18 UTC, Andrew8xx8 approved these changes

2020-05-09 19:22 UTC, merged